In [4]:
import numpy as np

In [5]:
list1=[2,3,4,5]
list2=[6,8,9,3]
np.array(list1)+np.array(list2)

array([ 8, 11, 13,  8])

In [6]:
arr_str=['Mercedes',6,'audi','feraari','tesla']
arr_num=(3,6,7,4,3)
print(type(arr_str))
print(type(arr_num))

<class 'list'>
<class 'tuple'>


In [7]:
np_arr_str=np.array(arr_str)
np_arr_num=np.array(arr_num)
print(np_arr_str)
print(np_arr_num)

['Mercedes' '6' 'audi' 'feraari' 'tesla']
[3 6 7 4 3]


In [8]:
#NumPy matrix

In [9]:
matrix1=np.array([(1,2),(3,4),(5,6)])
matrix1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
matrix1.shape

(3, 2)

In [11]:
#functions to create NumPy array
#using np.arange() function

In [12]:
arr2= np.arange(0,10,2)
print(arr2)

[0 2 4 6 8]


In [13]:
#using np.zeros()

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
arr=np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [51]:
#trigonometric_function
print('Sine Function:',np.sin(30))
print('Cosine Function:',np.cos(60))
print('Tan Function:',np.tan(0))

Sine Function: -0.9880316240928618
Cosine Function: -0.9524129804151563
Tan Function: 0.0


In [53]:
#exponents and logarithmic functions
np.exp(2)

7.38905609893065

In [55]:
arr1 = np.array([2,4,6])
np.exp(arr1)

array([  7.3890561 ,  54.59815003, 403.42879349])

In [67]:
print(np.log(2))
print(np.log10(1000))

0.6931471805599453
3.0


In [85]:
#arithmetic_operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,8])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(1/arr1)
print(arr1**arr2)

[ 5  7  9 11 13]
[-3 -3 -3 -3 -3]
[ 4 10 18 28 40]
[0.25       0.4        0.5        0.57142857 0.625     ]
[1.         0.5        0.33333333 0.25       0.2       ]
[     1     32    729  16384 390625]


In [97]:
#operations on matrices
matrix=np.arange(1,10).reshape(3,3)
print(matrix)
matrix1=np.eye(3)
print(matrix1)
print(matrix*matrix1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]


In [105]:
mat=np.arange(1,10).reshape(3,3)
mat1=np.arange(4,13).reshape(3,3)
print(mat+mat1)
print('\t')
print(mat-mat1)
print('\t')
print(mat*mat1)
print('\t')
print(mat/mat1)
print('\n')
print(mat@mat1)  #for dot product

[[ 5  7  9]
 [11 13 15]
 [17 19 21]]
	
[[-3 -3 -3]
 [-3 -3 -3]
 [-3 -3 -3]]
	
[[  4  10  18]
 [ 28  40  54]
 [ 70  88 108]]
	
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [0.7        0.72727273 0.75      ]]


[[ 48  54  60]
 [111 126 141]
 [174 198 222]]


In [107]:
np.linalg.multi_dot([mat,mat1]) #for dot product

array([[ 48,  54,  60],
       [111, 126, 141],
       [174, 198, 222]])

In [119]:
# x+2y+3z=10
# 2x+3y+z=15
# x+y+2z=20
m1=np.array([1,2,3,2,3,1,1,1,2]).reshape(3,3)
m2=np.array([10,15,20]).reshape(3,1)
#m3=np.array([x,y,z]).reshape(3,1)
x,y,z=np.linalg.solve(m1,m2)
print('x=',x)
print('y=',y)
print('z=',z)

x= [26.25]
y= [-13.75]
z= [3.75]


In [129]:
#transpose
m1=np.array([1,2,3,2,3,1,1,1,2]).reshape(3,3)
print(m1)
np.transpose(m1)
#or_use : m1.T

[[1 2 3]
 [2 3 1]
 [1 1 2]]


array([[1, 2, 1],
       [2, 3, 1],
       [3, 1, 2]])

In [143]:
print(np.max(m1))
print(np.min(m1))
print(np.sum(m1))

3
1
16


In [209]:
#producing random numbers
rand_mat = np.random.rand(5,5)
print(rand_mat)

[[0.12949805 0.16164642 0.88530807 0.26722863 0.07632794]
 [0.10308182 0.63983632 0.37383547 0.21085354 0.07442346]
 [0.31599596 0.82570758 0.73785995 0.55959207 0.69409471]
 [0.4620292  0.98246031 0.31555212 0.6801045  0.69636162]
 [0.19787176 0.95618244 0.90864455 0.04937842 0.26889984]]


In [211]:
matrix = np.random.rand(30)
print(matrix)
print('\t')
print(np.mean(matrix))
print(np.std(matrix))

[0.01097498 0.30463236 0.69799932 0.92368632 0.19998961 0.80684027
 0.25964899 0.35761459 0.48602767 0.68614311 0.18269096 0.96028761
 0.76919426 0.31569457 0.79952415 0.81125063 0.851987   0.05129215
 0.21303644 0.23600846 0.54843204 0.52176409 0.93592342 0.1910734
 0.24456868 0.07817134 0.22257071 0.74010621 0.54052944 0.29679654]
	
0.47481531032506086
0.2924558850161549


In [221]:
mat1= np.random.randint(2,6,10) #(low, high, size)
print(mat1)
mat2= np.random.randint(2,6,[5,1])
print(mat2)

[5 3 2 5 3 2 2 4 3 3]
[[2]
 [4]
 [5]
 [3]
 [3]]


In [223]:
mat1>3

array([ True, False, False,  True, False, False, False,  True, False,
       False])

In [227]:
mat1[mat1>3]

array([5, 5, 4])

In [243]:
#creating sub matrix
matrix=np.random.randint(1,30,[5,5])
print(matrix)
print(matrix[1:4,1:4]) #extracting second row-second column to fourth row-fourth column

[[21  5 21  7 19]
 [20  5 14 28 27]
 [14 25  1 23 28]
 [20 22 23 25 16]
 [18  2 26 11  3]]
[[ 5 14 28]
 [25  1 23]
 [22 23 25]]
